(cond ((eq system-type 'gnu/linux)
  (setq linarcx-shell "/bin/bash")
  (setq-default shell-file-name linarcx-shell)
  (setq-default explicit-shell-file-name linarcx-shell)
  (setq dap-lldb-debug-program '("/usr/bin/lldb-vscode"))
  (setq bmkp-current-bookmark-file "~/.emacs.d/bookmarks_linux.bmk")
  (setq dired-listing-switches "-lghA --time-style long-iso --group-directories-first")
  (global-set-key (kbd "M-t") (lambda () (interactive) (term linarcx-shell)))

  (eval-after-load "dired" '(progn
 	  (define-key dired-mode-map (kbd "C-c n") (lambda ()(interactive)(dired-sort-other "-lghA --time-style long-iso")))
 		(define-key dired-mode-map (kbd "C-c t") (lambda()(interactive)(dired-sort-other "-lghA --time-style long-iso -t")))
 		(define-key dired-mode-map (kbd "C-c s") (lambda()(interactive)(dired-sort-other "-lghA --time-style long-iso -S")))
 		(define-key dired-mode-map (kbd "C-c d") (lambda()(interactive)(dired-sort-other "-lghA --time-style long-iso --group-directories-first")))))

  (defun linarcx-run-commands-in-term (command)
    (interactive)
    (term linarcx-shell)
    (term-send-raw-string command)
    (term-send-raw-string "\n"))

  (defun linarcx-apps ()
    (interactive)
    (setq completions '(("Htop" "clear; exec sh -c \"stty eof q; htop; read x\"")
 		  ("Restart Tor" "clear; exec sh -c \"stty eof q; sudo sv restart tor; read x\"")
 		  ("Weather" "clear; exec sh -c \"stty eof q; curl wttr.in/tehran\?nqF; read x\"")
 		  ("IPAddress" "clear; exec sh -c \"stty eof q; curl eth0.me; read x\"")
 		  ("DNS" "clear; exec sh -c \"stty eof q; curl -L https://edns.ip-api.com/json; read x\"")
 		  ("CryptoCurrencies" "clear; exec sh -c \"stty eof q; curl rate.sx; read x\"")
 		  ("Jokes" "clear; exec sh -c \"stty eof q; curl https://icanhazdadjoke.com; read x\"")
 		  ("Covid19" "clear; exec sh -c \"stty eof q; curl snf-878293.vm.okeanos.grnet.gr; read x\"")
 		  ("BashMount" "bashmount.sh")
 		  ("Connect Android Phone(SSH)" "sshfs -p 2222 linarcx@192.168.1.33:/ ~/Device")
 		  ("All Kernels(vkpurge)" "clear; exec sh -c \"stty eof q; vkpurge list; read x\"")
 		  ("Remove Old Kernels(vkpurge)" "sudo vkpurge list | sort -V | head -n -3 | sudo xargs vkpurge rm")
 		  ("Network Interfaces(ifconfig -a)" "clear; exec sh -c \"stty eof q; ifconfig -a; read x\"")
 		  ("Disks and partitions (fdisk)" "clear; exec sh -c \"stty eof q; sudo fdisk -l; read x\"")
 		  ("FileSystem disk usage (df)" "clear; exec sh -c \"stty eof q; df -h; read x\"")
 		  ("Block devices (lsblk)" "clear; exec sh -c \"stty eof q; lsblk -a; read x\"")
 		  ("Block device attributes (blkid)" "clear; exec sh -c \"stty eof q; blkid; read x\"")
 		  ("Mounted filesystems" "clear; exec sh -c \"stty eof q; cat /proc/mounts; read x\"")
 		  ("Tcp/Udp Open ports (netstat)" "clear; exec sh -c \"stty eof q; netstat -lntu; read x\"")
 		  ("Unix sockets" "clear; exec sh -c \"stty eof q; netstat -a -p --unix; read x\"")
 		  ("All Services" "clear; exec sh -c \"stty eof q; ls /etc/sv; read x\"")
 		  ("Enabled Services" "clear; exec sh -c \"stty eof q; ls /var/service; read x\"")
 		  ("PCI devices (lspci)" "clear; exec sh -c \"stty eof q; lspci; read x\"")
 		  ("USB devices (lsusb)" "clear; exec sh -c \"stty eof q; lsusb; read x\"")
 		  ("Cpu Information (lscpu)" "clear; exec sh -c \"stty eof q; lscpu; read x\"")
 		  ("Kernel Modules (lsmod)" "clear; exec sh -c \"stty eof q; lsmod | sort; read x\"")
 		  ("Processes tree(pstree)" "clear; exec sh -c \"stty eof q; pstree; read x\"")
 		  ("LoggedIn users (lslogins)" "clear; exec sh -c \"stty eof q; lslogins; read x\"")
 		  ("Update Grub" "sudo grub-mkconfig -o /boot/grub/grub.cfg && sudo grub-install /dev/sda")
 		  ("Namespaces (lsns)" "clear; exec sh -c \"stty eof q; lsns; read x\"")
 		 ))
    (setq choiceList(cdr (assoc (completing-read "Choose: " completions) completions)))
    (setq choice (car choiceList))
    (linarcx-run-commands-in-term choice))
      (global-set-key (kbd "<f2> a") 'linarcx-apps)
  ))

(provide 'setup-linux)
